"""生成中英法律术语库 xlsx，供管理后台导入。

输出格式（与 backend/app/api/terms.py:_import_rows 要求一致）：
列顺序：中文术语 | 目标语言术语 | 语种方向 | 领域标签 | 优先级 | 备注

覆盖领域：
- 合同法（Contract Law）
- 公司法（Corporate Law）
- 诉讼与仲裁（Litigation & Arbitration）
- 知识产权（Intellectual Property）
- 劳动法（Employment Law）
- 物权与担保（Property & Security）
- 侵权法（Tort Law）
- 证券与金融（Securities & Finance）
- 刑事（Criminal Law）
- 程序与证据（Procedure & Evidence）
- 通用法律表达（General legal expressions）
"""
from __future__ import annotations

import openpyxl


# 列顺序：中文术语, 目标语言术语, 语种方向, 领域标签, 优先级, 备注
# 优先级：strict（强制） / preferred（优先）
TERMS: list[tuple[str, str, str, str, str, str]] = [

    # ============================================================
    # 一、合同法（Contract Law）
    # ============================================================
    ("要约", "offer", "zh→en", "合同", "strict", "合同订立的意思表示"),
    ("承诺", "acceptance", "zh→en", "合同", "strict", "同意要约的意思表示"),
    ("要约邀请", "invitation to offer", "zh→en", "合同", "preferred", "引诱他人向自己发出要约"),
    ("缔约过失责任", "culpa in contrahendo", "zh→en", "合同", "preferred", "缔约阶段的过错责任"),
    ("合同成立", "conclusion of contract", "zh→en", "合同", "strict", ""),
    ("合同生效", "effectiveness of contract", "zh→en", "合同", "strict", ""),
    ("合同无效", "invalidity of contract", "zh→en", "合同", "strict", ""),
    ("可撤销合同", "voidable contract", "zh→en", "合同", "strict", ""),
    ("效力待定合同", "contract with pending validity", "zh→en", "合同", "preferred", ""),
    ("附条件合同", "contract subject to conditions", "zh→en", "合同", "preferred", ""),
    ("附期限合同", "contract subject to a time limit", "zh→en", "合同", "preferred", ""),
    ("违约责任", "liability for breach of contract", "zh→en", "合同", "strict", ""),
    ("预期违约", "anticipatory breach", "zh→en", "合同", "strict", ""),
    ("实际违约", "actual breach", "zh→en", "合同", "preferred", ""),
    ("根本违约", "fundamental breach", "zh→en", "合同", "strict", ""),
    ("继续履行", "specific performance", "zh→en", "合同", "strict", "又称强制履行"),
    ("采取补救措施", "adopt remedial measures", "zh→en", "合同", "preferred", ""),
    ("赔偿损失", "damages", "zh→en", "合同", "strict", "损害赔偿"),
    ("支付违约金", "payment of liquidated damages", "zh→en", "合同", "strict", ""),
    ("定金", "deposit", "zh→en", "合同", "strict", "注意与 earnest money 区分"),
    ("定金罚则", "forfeiture of deposit", "zh→en", "合同", "preferred", ""),
    ("合同解除", "termination of contract", "zh→en", "合同", "strict", ""),
    ("协议解除", "termination by agreement", "zh→en", "合同", "preferred", ""),
    ("法定解除", "statutory termination", "zh→en", "合同", "preferred", ""),
    ("不可抗力", "force majeure", "zh→en", "合同", "strict", "法定免责事由"),
    ("情势变更", "change of circumstances", "zh→en", "合同", "strict", "frustration 的近义概念"),
    ("减损义务", "duty to mitigate loss", "zh→en", "合同", "preferred", "非违约方的义务"),
    ("同时履行抗辩权", "defense of simultaneous performance", "zh→en", "合同", "preferred", ""),
    ("先履行抗辩权", "defense of prior performance", "zh→en", "合同", "preferred", ""),
    ("不安抗辩权", "defense of insecurity", "zh→en", "合同", "preferred", ""),
    ("债权转让", "assignment of creditor's rights", "zh→en", "合同", "strict", ""),
    ("债务转移", "transfer of debt", "zh→en", "合同", "strict", ""),
    ("债务加入", "assumption of debt", "zh→en", "合同", "preferred", ""),
    ("抵销", "set-off", "zh→en", "合同", "strict", ""),
    ("提存", "deposit with a depository", "zh→en", "合同", "preferred", ""),
    ("免除", "waiver", "zh→en", "合同", "preferred", ""),
    ("混同", "merger of rights", "zh→en", "合同", "preferred", "债权债务同归一人"),
    ("标的", "subject matter", "zh→en", "合同", "strict", ""),
    ("对价", "consideration", "zh→en", "合同", "strict", "英美法概念"),
    ("格式条款", "standard terms", "zh→en", "合同", "strict", "又称附合条款"),
    ("免责条款", "exemption clause", "zh→en", "合同", "preferred", ""),
    ("保密条款", "confidentiality clause", "zh→en", "合同", "preferred", ""),
    ("竞业禁止", "non-compete", "zh→en", "合同", "strict", ""),
    ("排他条款", "exclusivity clause", "zh→en", "合同", "preferred", ""),
    ("意向书", "letter of intent", "zh→en", "合同", "preferred", "LOI"),
    ("谅解备忘录", "memorandum of understanding", "zh→en", "合同", "preferred", "MOU"),
    ("框架协议", "framework agreement", "zh→en", "合同", "preferred", ""),
    ("补充协议", "supplementary agreement", "zh→en", "合同", "preferred", ""),
    ("转让协议", "transfer agreement", "zh→en", "合同", "preferred", ""),
    ("和解协议", "settlement agreement", "zh→en", "合同", "preferred", ""),
    ("违约金", "liquidated damages", "zh→en", "合同", "strict", ""),
    ("滞纳金", "late payment fee", "zh→en", "合同", "preferred", ""),
    ("损害赔偿", "damages", "zh→en", "合同", "strict", ""),
    ("间接损失", "indirect damages", "zh→en", "合同", "preferred", "consequential loss"),
    ("可得利益损失", "loss of expected benefits", "zh→en", "合同", "preferred", ""),
    ("瑕疵", "defect", "zh→en", "合同", "strict", ""),
    ("瑕疵担保责任", "warranty against defects", "zh→en", "合同", "preferred", ""),
    ("交付", "delivery", "zh→en", "合同", "strict", ""),
    ("风险转移", "passing of risk", "zh→en", "合同", "strict", ""),
    ("所有权保留", "retention of title", "zh→en", "合同", "preferred", ""),
    ("试用买卖", "sale on approval", "zh→en", "合同", "preferred", ""),
    ("分期付款买卖", "installment sale", "zh→en", "合同", "preferred", ""),
    ("招投标", "bidding", "zh→en", "合同", "preferred", ""),
    ("中标", "winning of bid", "zh→en", "合同", "preferred", ""),
    ("居间合同", "brokerage contract", "zh→en", "合同", "preferred", ""),

    # ============================================================
    # 二、公司法（Corporate Law）
    # ============================================================
    ("有限责任公司", "limited liability company", "zh→en", "公司法", "strict", "LLC"),
    ("股份有限公司", "company limited by shares", "zh→en", "公司法", "strict", ""),
    ("发起人", "promoter", "zh→en", "公司法", "strict", ""),
    ("股东", "shareholder", "zh→en", "公司法", "strict", ""),
    ("控股股东", "controlling shareholder", "zh→en", "公司法", "strict", ""),
    ("实际控制人", "actual controller", "zh→en", "公司法", "strict", ""),
    ("董事", "director", "zh→en", "公司法", "strict", ""),
    ("独立董事", "independent director", "zh→en", "公司法", "strict", ""),
    ("监事", "supervisor", "zh→en", "公司法", "strict", ""),
    ("高级管理人员", "senior management", "zh→en", "公司法", "strict", ""),
    ("法定代表人", "legal representative", "zh→en", "公司法", "strict", ""),
    ("公司章程", "articles of association", "zh→en", "公司法", "strict", "又称 company bylaws"),
    ("股东会", "shareholders' meeting", "zh→en", "公司法", "strict", ""),
    ("董事会", "board of directors", "zh→en", "公司法", "strict", ""),
    ("监事会", "board of supervisors", "zh→en", "公司法", "strict", ""),
    ("注册资本", "registered capital", "zh→en", "公司法", "strict", ""),
    ("认缴出资", "subscribed capital contribution", "zh→en", "公司法", "strict", ""),
    ("实缴出资", "paid-in capital", "zh→en", "公司法", "strict", ""),
    ("股权", "equity interest", "zh→en", "公司法", "strict", ""),
    ("股份转让", "transfer of shares", "zh→en", "公司法", "strict", ""),
    ("股权转让", "transfer of equity", "zh→en", "公司法", "strict", ""),
    ("优先购买权", "right of first refusal", "zh→en", "公司法", "strict", "ROFR"),
    ("公司分立", "corporate division", "zh→en", "公司法", "preferred", ""),
    ("公司合并", "corporate merger", "zh→en", "公司法", "preferred", ""),
    ("公司解散", "dissolution of company", "zh→en", "公司法", "strict", ""),
    ("公司清算", "liquidation of company", "zh→en", "公司法", "strict", ""),
    ("清算组", "liquidation group", "zh→en", "公司法", "preferred", "liquidator"),
    ("破产清算", "bankruptcy liquidation", "zh→en", "公司法", "strict", ""),
    ("重整", "reorganization", "zh→en", "公司法", "strict", ""),
    ("和解", "composition", "zh→en", "公司法", "preferred", "破产和解"),
    ("母公司", "parent company", "zh→en", "公司法", "strict", ""),
    ("子公司", "subsidiary", "zh→en", "公司法", "strict", ""),
    ("分公司", "branch", "zh→en", "公司法", "strict", "branch office"),
    ("办事处", "representative office", "zh→en", "公司法", "preferred", "RO"),
    ("关联交易", "connected transaction", "zh→en", "公司法", "strict", "related party transaction"),
    ("关联关系", "connected relationship", "zh→en", "公司法", "preferred", ""),
    ("忠实义务", "duty of loyalty", "zh→en", "公司法", "strict", ""),
    ("勤勉义务", "duty of diligence", "zh→en", "公司法", "strict", "duty of care"),
    ("竞业禁止义务", "non-competition obligation", "zh→en", "公司法", "preferred", ""),
    ("派生诉讼", "derivative action", "zh→en", "公司法", "preferred", "股东代表诉讼"),
    ("股东代表诉讼", "shareholder derivative suit", "zh→en", "公司法", "strict", ""),
    ("公司债券", "corporate bond", "zh→en", "公司法", "strict", ""),
    ("增资", "capital increase", "zh→en", "公司法", "preferred", "increase of capital"),
    ("减资", "capital reduction", "zh→en", "公司法", "preferred", "reduction of capital"),
    ("验资", "capital verification", "zh→en", "公司法", "preferred", ""),
    ("营业执照", "business license", "zh→en", "公司法", "strict", ""),
    ("外商投资企业", "foreign-invested enterprise", "zh→en", "公司法", "strict", "FIE"),

    # ============================================================
    # 三、诉讼与仲裁（Litigation & Arbitration）
    # ============================================================
    ("原告", "plaintiff", "zh→en", "诉讼", "strict", "民事诉讼中"),
    ("被告", "defendant", "zh→en", "诉讼", "strict", "民事诉讼中"),
    ("上诉人", "appellant", "zh→en", "诉讼", "strict", ""),
    ("被上诉人", "appellee", "zh→en", "诉讼", "strict", "respondent"),
    ("第三人", "third party", "zh→en", "诉讼", "strict", "有独立请求权/无独立请求权"),
    ("有独立请求权第三人", "third party with independent claim", "zh→en", "诉讼", "preferred", ""),
    ("无独立请求权第三人", "third party without independent claim", "zh→en", "诉讼", "preferred", ""),
    ("诉讼代理人", "agent ad litem", "zh→en", "诉讼", "preferred", "litigation agent"),
    ("委托代理人", "authorized representative", "zh→en", "诉讼", "preferred", ""),
    ("诉讼请求", "claim", "zh→en", "诉讼", "strict", "claims"),
    ("反诉", "counterclaim", "zh→en", "诉讼", "strict", ""),
    ("管辖权", "jurisdiction", "zh→en", "诉讼", "strict", ""),
    ("管辖权异议", "jurisdictional objection", "zh→en", "诉讼", "strict", ""),
    ("级别管辖", "jurisdiction by level", "zh→en", "诉讼", "preferred", ""),
    ("地域管辖", "territorial jurisdiction", "zh→en", "诉讼", "preferred", ""),
    ("专属管辖", "exclusive jurisdiction", "zh→en", "诉讼", "preferred", ""),
    ("协议管辖", "agreed jurisdiction", "zh→en", "诉讼", "preferred", ""),
    ("回避", "withdrawal", "zh→en", "诉讼", "preferred", "recusal"),
    ("保全", "preservation", "zh→en", "诉讼", "strict", "property preservation"),
    ("财产保全", "property preservation", "zh→en", "诉讼", "strict", ""),
    ("证据保全", "evidence preservation", "zh→en", "诉讼", "strict", ""),
    ("诉前保全", "pre-litigation preservation", "zh→en", "诉讼", "preferred", ""),
    ("诉讼保全", "litigation preservation", "zh→en", "诉讼", "preferred", ""),
    ("先予执行", "advance execution", "zh→en", "诉讼", "preferred", ""),
    ("举证责任", "burden of proof", "zh→en", "诉讼", "strict", ""),
    ("举证期限", "time limit for producing evidence", "zh→en", "诉讼", "preferred", ""),
    ("证据交换", "exchange of evidence", "zh→en", "诉讼", "preferred", ""),
    ("质证", "cross-examination", "zh→en", "诉讼", "strict", ""),
    ("书证", "documentary evidence", "zh→en", "诉讼", "strict", ""),
    ("物证", "physical evidence", "zh→en", "诉讼", "strict", ""),
    ("证人证言", "witness testimony", "zh→en", "诉讼", "strict", ""),
    ("鉴定意见", "expert opinion", "zh→en", "诉讼", "strict", "expert conclusion"),
    ("勘验笔录", "record of inspection", "zh→en", "诉讼", "preferred", ""),
    ("视听资料", "audio-visual material", "zh→en", "诉讼", "preferred", ""),
    ("电子数据", "electronic data", "zh→en", "诉讼", "strict", "digital evidence"),
    ("一审", "first instance", "zh→en", "诉讼", "strict", "trial court"),
    ("二审", "second instance", "zh→en", "诉讼", "strict", "appellate court"),
    ("审判监督程序", "trial supervision procedure", "zh→en", "诉讼", "preferred", "再审程序"),
    ("再审", "retrial", "zh→en", "诉讼", "strict", "reopening of the case"),
    ("撤诉", "withdrawal of lawsuit", "zh→en", "诉讼", "preferred", ""),
    ("缺席判决", "default judgment", "zh→en", "诉讼", "strict", ""),
    ("裁定", "ruling", "zh→en", "诉讼", "strict", "对程序事项"),
    ("判决", "judgment", "zh→en", "诉讼", "strict", "对实体事项"),
    ("调解书", "mediation statement", "zh→en", "诉讼", "preferred", ""),
    ("执行", "enforcement", "zh→en", "诉讼", "strict", "execution"),
    ("强制执行", "compulsory enforcement", "zh→en", "诉讼", "strict", ""),
    ("执行异议", "enforcement objection", "zh→en", "诉讼", "preferred", ""),
    ("案外人异议", "objection by a person not party to the case", "zh→en", "诉讼", "preferred", ""),
    ("仲裁", "arbitration", "zh→en", "诉讼", "strict", ""),
    ("仲裁协议", "arbitration agreement", "zh→en", "诉讼", "strict", ""),
    ("仲裁条款", "arbitration clause", "zh→en", "诉讼", "strict", ""),
    ("仲裁庭", "arbitral tribunal", "zh→en", "诉讼", "strict", ""),
    ("仲裁员", "arbitrator", "zh→en", "诉讼", "strict", ""),
    ("仲裁裁决", "arbitral award", "zh→en", "诉讼", "strict", ""),
    ("仲裁地", "seat of arbitration", "zh→en", "诉讼", "preferred", ""),
    ("国际商事仲裁", "international commercial arbitration", "zh→en", "诉讼", "preferred", ""),
    ("承认与执行外国判决", "recognition and enforcement of foreign judgments", "zh→en", "诉讼", "preferred", ""),
    ("纽约公约", "New York Convention", "zh→en", "诉讼", "preferred", "《承认及执行外国仲裁裁决公约》"),
    ("诉讼时效", "limitation period", "zh→en", "诉讼", "strict", "statute of limitations"),
    ("诉讼时效中断", "interruption of limitation period", "zh→en", "诉讼", "preferred", ""),
    ("诉讼时效中止", "suspension of limitation period", "zh→en", "诉讼", "preferred", ""),

    # ============================================================
    # 四、知识产权（Intellectual Property）
    # ============================================================
    ("知识产权", "intellectual property", "zh→en", "知识产权", "strict", "IP"),
    ("著作权", "copyright", "zh→en", "知识产权", "strict", ""),
    ("版权", "copyright", "zh→en", "知识产权", "strict", ""),
    ("著作权人", "copyright owner", "zh→en", "知识产权", "strict", ""),
    ("发表权", "right of publication", "zh→en", "知识产权", "strict", ""),
    ("署名权", "right of authorship", "zh→en", "知识产权", "strict", ""),
    ("修改权", "right of alteration", "zh→en", "知识产权", "strict", ""),
    ("保护作品完整权", "right of integrity", "zh→en", "知识产权", "preferred", ""),
    ("复制权", "right of reproduction", "zh→en", "知识产权", "strict", ""),
    ("发行权", "right of distribution", "zh→en", "知识产权", "strict", ""),
    ("出租权", "right of rental", "zh→en", "知识产权", "preferred", ""),
    ("展览权", "right of exhibition", "zh→en", "知识产权", "preferred", ""),
    ("表演权", "right of performance", "zh→en", "知识产权", "strict", ""),
    ("放映权", "right of presentation", "zh→en", "知识产权", "preferred", ""),
    ("广播权", "right of broadcasting", "zh→en", "知识产权", "strict", ""),
    ("信息网络传播权", "right of information network dissemination", "zh→en", "知识产权", "strict", ""),
    ("摄制权", "right of cinematographic adaptation", "zh→en", "知识产权", "preferred", ""),
    ("改编权", "right of adaptation", "zh→en", "知识产权", "strict", ""),
    ("翻译权", "right of translation", "zh→en", "知识产权", "strict", ""),
    ("汇编权", "right of compilation", "zh→en", "知识产权", "preferred", ""),
    ("商标", "trademark", "zh→en", "知识产权", "strict", ""),
    ("注册商标", "registered trademark", "zh→en", "知识产权", "strict", ""),
    ("商标注册申请", "trademark registration application", "zh→en", "知识产权", "preferred", ""),
    ("商标权", "trademark right", "zh→en", "知识产权", "strict", ""),
    ("驰名商标", "well-known trademark", "zh→en", "知识产权", "strict", ""),
    ("商标侵权", "trademark infringement", "zh→en", "知识产权", "strict", ""),
    ("专利", "patent", "zh→en", "知识产权", "strict", ""),
    ("发明专利", "invention patent", "zh→en", "知识产权", "strict", ""),
    ("实用新型", "utility model", "zh→en", "知识产权", "strict", ""),
    ("外观设计", "industrial design", "zh→en", "知识产权", "strict", ""),
    ("专利权人", "patentee", "zh→en", "知识产权", "strict", ""),
    ("专利侵权", "patent infringement", "zh→en", "知识产权", "strict", ""),
    ("权利要求", "claims", "zh→en", "知识产权", "strict", "patent claims"),
    ("说明书", "description", "zh→en", "知识产权", "preferred", "patent specification"),
    ("优先权", "right of priority", "zh→en", "知识产权", "strict", ""),
    ("商业秘密", "trade secret", "zh→en", "知识产权", "strict", ""),
    ("不正当竞争", "unfair competition", "zh→en", "知识产权", "strict", ""),
    ("反不正当竞争法", "Anti-Unfair Competition Law", "zh→en", "知识产权", "preferred", ""),
    ("反垄断法", "Anti-Monopoly Law", "zh→en", "知识产权", "preferred", ""),
    ("许可", "license", "zh→en", "知识产权", "strict", ""),
    ("独占许可", "exclusive license", "zh→en", "知识产权", "strict", ""),
    ("排他许可", "sole license", "zh→en", "知识产权", "preferred", ""),
    ("普通许可", "non-exclusive license", "zh→en", "知识产权", "preferred", ""),
    ("许可人", "licensor", "zh→en", "知识产权", "strict", ""),
    ("被许可人", "licensee", "zh→en", "知识产权", "strict", ""),
    ("转让", "assignment", "zh→en", "知识产权", "strict", "transfer"),
    ("合理使用", "fair use", "zh→en", "知识产权", "strict", ""),
    ("法定许可", "statutory license", "zh→en", "知识产权", "preferred", ""),
    ("强制许可", "compulsory license", "zh→en", "知识产权", "preferred", ""),
    ("侵权损害赔偿", "damages for infringement", "zh→en", "知识产权", "strict", ""),
    ("停止侵权", "cessation of infringement", "zh→en", "知识产权", "strict", "injunction"),
    ("消除影响", "elimination of adverse effects", "zh→en", "知识产权", "preferred", ""),
    ("赔礼道歉", "apology", "zh→en", "知识产权", "preferred", ""),

    # ============================================================
    # 五、劳动法（Employment Law）
    # ============================================================
    ("劳动合同", "employment contract", "zh→en", "劳动法", "strict", "labor contract"),
    ("用人单位", "employer", "zh→en", "劳动法", "strict", ""),
    ("劳动者", "employee", "zh→en", "劳动法", "strict", "worker"),
    ("固定期限劳动合同", "fixed-term employment contract", "zh→en", "劳动法", "strict", ""),
    ("无固定期限劳动合同", "open-ended employment contract", "zh→en", "劳动法", "strict", ""),
    ("以完成一定工作任务为期限的劳动合同", "employment contract with a term of completion of a certain task", "zh→en", "劳动法", "preferred", ""),
    ("试用期", "probation period", "zh→en", "劳动法", "strict", ""),
    ("工资", "wages", "zh→en", "劳动法", "strict", "salary"),
    ("最低工资标准", "minimum wage standard", "zh→en", "劳动法", "strict", ""),
    ("加班费", "overtime pay", "zh→en", "劳动法", "strict", ""),
    ("经济补偿", "severance pay", "zh→en", "劳动法", "strict", "economic compensation"),
    ("经济赔偿金", "compensatory damages", "zh→en", "劳动法", "preferred", "违法解除的赔偿"),
    ("解除劳动合同", "termination of employment contract", "zh→en", "劳动法", "strict", ""),
    ("违法解除劳动合同", "wrongful termination", "zh→en", "劳动法", "strict", ""),
    ("协商解除", "termination by mutual agreement", "zh→en", "劳动法", "preferred", ""),
    ("裁员", "layoff", "zh→en", "劳动法", "strict", "economic layoff"),
    ("经济性裁员", "economic layoff", "zh→en", "劳动法", "strict", ""),
    ("竞业限制", "post-termination non-compete", "zh→en", "劳动法", "strict", ""),
    ("保密义务", "duty of confidentiality", "zh→en", "劳动法", "strict", ""),
    ("服务期", "service period", "zh→en", "劳动法", "preferred", ""),
    ("违约金", "liquidated damages", "zh→en", "劳动法", "preferred", ""),
    ("工伤", "work-related injury", "zh→en", "劳动法", "strict", ""),
    ("工伤保险", "work-related injury insurance", "zh→en", "劳动法", "strict", ""),
    ("社会保险", "social insurance", "zh→en", "劳动法", "strict", ""),
    ("住房公积金", "housing provident fund", "zh→en", "劳动法", "strict", ""),
    ("带薪年休假", "paid annual leave", "zh→en", "劳动法", "strict", ""),
    ("劳动争议", "labor dispute", "zh→en", "劳动法", "strict", ""),
    ("劳动仲裁", "labor arbitration", "zh→en", "劳动法", "strict", ""),
    ("工会", "trade union", "zh→en", "劳动法", "strict", "labor union"),
    ("集体合同", "collective agreement", "zh→en", "劳动法", "strict", "collective bargaining agreement"),
    ("劳务派遣", "labor dispatch", "zh→en", "劳动法", "strict", ""),
    ("非全日制用工", "part-time employment", "zh→en", "劳动法", "preferred", ""),

    # ============================================================
    # 六、物权与担保（Property & Security）
    # ============================================================
    ("物权", "property right", "zh→en", "物权", "strict", "real right"),
    ("所有权", "ownership", "zh→en", "物权", "strict", ""),
    ("用益物权", "usufructuary right", "zh→en", "物权", "strict", ""),
    ("担保物权", "security interest", "zh→en", "物权", "strict", ""),
    ("抵押", "mortgage", "zh→en", "物权", "strict", ""),
    ("抵押权", "mortgage right", "zh→en", "物权", "strict", ""),
    ("抵押人", "mortgagor", "zh→en", "物权", "strict", ""),
    ("抵押权人", "mortgagee", "zh→en", "物权", "strict", ""),
    ("质押", "pledge", "zh→en", "物权", "strict", ""),
    ("动产质押", "chattel pledge", "zh→en", "物权", "strict", ""),
    ("权利质押", "pledge of rights", "zh→en", "物权", "preferred", ""),
    ("质权人", "pledgee", "zh→en", "物权", "strict", ""),
    ("出质人", "pledgor", "zh→en", "物权", "strict", ""),
    ("留置权", "lien", "zh→en", "物权", "strict", ""),
    ("保证", "guarantee", "zh→en", "物权", "strict", ""),
    ("保证人", "guarantor", "zh→en", "物权", "strict", ""),
    ("保证合同", "guarantee contract", "zh→en", "物权", "strict", ""),
    ("一般保证", "general guarantee", "zh→en", "物权", "preferred", ""),
    ("连带责任保证", "joint and several liability guarantee", "zh→en", "物权", "strict", ""),
    ("连带责任", "joint and several liability", "zh→en", "物权", "strict", ""),
    ("反担保", "counter-guarantee", "zh→en", "物权", "preferred", ""),
    ("定金", "earnest money", "zh→en", "物权", "strict", ""),
    ("预告登记", "advance registration", "zh→en", "物权", "preferred", ""),
    ("善意取得", "bona fide acquisition", "zh→en", "物权", "strict", ""),
    ("共有", "co-ownership", "zh→en", "物权", "strict", ""),
    ("按份共有", "co-ownership by shares", "zh→en", "物权", "preferred", ""),
    ("共同共有", "co-ownership in common", "zh→en", "物权", "preferred", ""),
    ("相邻关系", "neighboring relationship", "zh→en", "物权", "preferred", ""),
    ("宅基地使用权", "right to use homestead", "zh→en", "物权", "preferred", ""),
    ("土地承包经营权", "right to contracted management of land", "zh→en", "物权", "preferred", ""),
    ("建设用地使用权", "right to use construction land", "zh→en", "物权", "preferred", ""),
    ("典权", "right of antichresis", "zh→en", "物权", "preferred", ""),

    # ============================================================
    # 七、侵权法（Tort Law）
    # ============================================================
    ("侵权", "tort", "zh→en", "侵权", "strict", "infringement"),
    ("侵权行为", "tortious act", "zh→en", "侵权", "strict", ""),
    ("侵权人", "tortfeasor", "zh→en", "侵权", "strict", ""),
    ("被侵权人", "injured party", "zh→en", "侵权", "strict", ""),
    ("过错责任", "fault liability", "zh→en", "侵权", "strict", ""),
    ("无过错责任", "strict liability", "zh→en", "侵权", "strict", "no-fault liability"),
    ("过错推定", "presumption of fault", "zh→en", "侵权", "preferred", ""),
    ("公平责任", "equitable liability", "zh→en", "侵权", "preferred", ""),
    ("共同侵权", "joint tort", "zh→en", "侵权", "strict", ""),
    ("教唆", "instigation", "zh→en", "侵权", "preferred", ""),
    ("帮助", "assistance", "zh→en", "侵权", "preferred", ""),
    ("损害", "damage", "zh→en", "侵权", "strict", ""),
    ("实际损害", "actual damage", "zh→en", "侵权", "preferred", ""),
    ("精神损害", "mental distress", "zh→en", "侵权", "strict", "non-pecuniary damage"),
    ("精神损害赔偿", "compensation for mental distress", "zh→en", "侵权", "strict", ""),
    ("惩罚性赔偿", "punitive damages", "zh→en", "侵权", "strict", ""),
    ("因果关系", "causation", "zh→en", "侵权", "strict", ""),
    ("相当因果关系", "adequate causation", "zh→en", "侵权", "preferred", ""),
    ("医疗事故", "medical malpractice", "zh→en", "侵权", "strict", ""),
    ("交通事故", "traffic accident", "zh→en", "侵权", "preferred", ""),
    ("产品责任", "product liability", "zh→en", "侵权", "strict", ""),
    ("缺陷产品", "defective product", "zh→en", "侵权", "strict", ""),
    ("环境污染责任", "environmental pollution liability", "zh→en", "侵权", "preferred", ""),
    ("高度危险责任", "liability for ultra-hazardous activities", "zh→en", "侵权", "preferred", ""),
    ("饲养动物损害责任", "liability for damage caused by kept animals", "zh→en", "侵权", "preferred", ""),
    ("建筑物倒塌责任", "liability for collapse of buildings", "zh→en", "侵权", "preferred", ""),
    ("高空抛物", "high-altitude object throwing", "zh→en", "侵权", "preferred", ""),
    ("正当防卫", "legitimate defense", "zh→en", "侵权", "strict", "self-defense"),
    ("紧急避险", "emergency avoidance", "zh→en", "侵权", "strict", "necessity"),
    ("自助行为", "self-help", "zh→en", "侵权", "preferred", ""),

    # ============================================================
    # 八、证券与金融（Securities & Finance）
    # ============================================================
    ("证券", "securities", "zh→en", "证券", "strict", ""),
    ("股票", "stock", "zh→en", "证券", "strict", "shares"),
    ("债券", "bond", "zh→en", "证券", "strict", ""),
    ("基金", "fund", "zh→en", "证券", "strict", ""),
    ("公募基金", "public fund", "zh→en", "证券", "preferred", ""),
    ("私募基金", "private fund", "zh→en", "证券", "strict", ""),
    ("首次公开发行", "initial public offering", "zh→en", "证券", "strict", "IPO"),
    ("上市公司", "listed company", "zh→en", "证券", "strict", ""),
    ("信息披露", "information disclosure", "zh→en", "证券", "strict", ""),
    ("内幕交易", "insider trading", "zh→en", "证券", "strict", ""),
    ("内幕信息", "inside information", "zh→en", "证券", "strict", ""),
    ("操纵市场", "market manipulation", "zh→en", "证券", "strict", ""),
    ("虚假陈述", "false statement", "zh→en", "证券", "strict", ""),
    ("欺诈发行", "fraudulent issuance", "zh→en", "证券", "preferred", ""),
    ("收购", "acquisition", "zh→en", "证券", "strict", "takeover"),
    ("要约收购", "tender offer", "zh→en", "证券", "strict", ""),
    ("协议收购", "acquisition by agreement", "zh→en", "证券", "preferred", ""),
    ("重大资产重组", "major asset restructuring", "zh→en", "证券", "strict", ""),
    ("借壳上市", "backdoor listing", "zh→en", "证券", "preferred", ""),
    ("关联交易", "connected transaction", "zh→en", "证券", "strict", ""),
    ("短线交易", "short-swing trading", "zh→en", "证券", "preferred", ""),
    ("大股东", "major shareholder", "zh→en", "证券", "strict", ""),
    ("实际控制人", "actual controller", "zh→en", "证券", "strict", ""),
    ("保荐人", "sponsor", "zh→en", "证券", "strict", ""),
    ("保荐机构", "sponsoring institution", "zh→en", "证券", "preferred", ""),
    ("承销", "underwriting", "zh→en", "证券", "strict", ""),
    ("承销商", "underwriter", "zh→en", "证券", "strict", ""),
    ("证券公司", "securities company", "zh→en", "证券", "strict", ""),
    ("期货", "futures", "zh→en", "证券", "strict", ""),
    ("期权", "options", "zh→en", "证券", "strict", ""),
    ("衍生品", "derivatives", "zh→en", "证券", "strict", ""),
    ("融资融券", "margin trading and short selling", "zh→en", "证券", "preferred", ""),
    ("贷款", "loan", "zh→en", "金融", "strict", ""),
    ("借款合同", "loan contract", "zh→en", "金融", "strict", ""),
    ("贷款人", "lender", "zh→en", "金融", "strict", ""),
    ("借款人", "borrower", "zh→en", "金融", "strict", ""),
    ("利率", "interest rate", "zh→en", "金融", "strict", ""),
    ("复利", "compound interest", "zh→en", "金融", "preferred", ""),
    ("逾期利息", "overdue interest", "zh→en", "金融", "preferred", ""),
    ("担保", "security", "zh→en", "金融", "strict", "collateral"),
    ("信用证", "letter of credit", "zh→en", "金融", "strict", "L/C"),
    ("保函", "letter of guarantee", "zh→en", "金融", "strict", ""),
    ("汇票", "bill of exchange", "zh→en", "金融", "strict", ""),
    ("本票", "promissory note", "zh→en", "金融", "strict", ""),
    ("支票", "check", "zh→en", "金融", "strict", "cheque"),
    ("票据", "negotiable instrument", "zh→en", "金融", "strict", ""),
    ("背书", "endorsement", "zh→en", "金融", "strict", ""),
    ("承兑", "acceptance", "zh→en", "金融", "strict", ""),
    ("追索权", "right of recourse", "zh→en", "金融", "strict", ""),

    # ============================================================
    # 九、刑事（Criminal Law）
    # ============================================================
    ("犯罪", "crime", "zh→en", "刑事", "strict", "offense"),
    ("犯罪嫌疑人", "criminal suspect", "zh→en", "刑事", "strict", ""),
    ("被告人", "the accused", "zh→en", "刑事", "strict", "defendant in criminal cases"),
    ("公诉人", "public prosecutor", "zh→en", "刑事", "strict", ""),
    ("自首", "voluntary surrender", "zh→en", "刑事", "strict", ""),
    ("立功", "meritorious service", "zh→en", "刑事", "preferred", ""),
    ("累犯", "recidivist", "zh→en", "刑事", "strict", ""),
    ("主犯", "principal offender", "zh→en", "刑事", "strict", ""),
    ("从犯", "accomplice", "zh→en", "刑事", "strict", ""),
    ("胁从犯", "coerced accomplice", "zh→en", "刑事", "preferred", ""),
    ("教唆犯", "instigator", "zh→en", "刑事", "preferred", ""),
    ("故意犯罪", "intentional crime", "zh→en", "刑事", "strict", ""),
    ("过失犯罪", "negligent crime", "zh→en", "刑事", "strict", ""),
    ("正当防卫", "legitimate defense", "zh→en", "刑事", "strict", "justifiable defense"),
    ("紧急避险", "emergency avoidance", "zh→en", "刑事", "strict", ""),
    ("犯罪未遂", "attempted crime", "zh→en", "刑事", "strict", ""),
    ("犯罪中止", "suspension of crime", "zh→en", "刑事", "strict", ""),
    ("犯罪预备", "preparation for crime", "zh→en", "刑事", "preferred", ""),
    ("共同犯罪", "joint crime", "zh→en", "刑事", "strict", ""),
    ("管制", "public surveillance", "zh→en", "刑事", "preferred", ""),
    ("拘役", "criminal detention", "zh→en", "刑事", "preferred", ""),
    ("有期徒刑", "fixed-term imprisonment", "zh→en", "刑事", "strict", ""),
    ("无期徒刑", "life imprisonment", "zh→en", "刑事", "strict", ""),
    ("死刑", "death penalty", "zh→en", "刑事", "strict", ""),
    ("罚金", "fine", "zh→en", "刑事", "strict", ""),
    ("剥夺政治权利", "deprivation of political rights", "zh→en", "刑事", "preferred", ""),
    ("没收财产", "confiscation of property", "zh→en", "刑事", "preferred", ""),
    ("缓刑", "probation", "zh→en", "刑事", "strict", "suspended sentence"),
    ("减刑", "commutation of sentence", "zh→en", "刑事", "preferred", ""),
    ("假释", "parole", "zh→en", "刑事", "strict", ""),
    ("追诉时效", "statute of limitations for prosecution", "zh→en", "刑事", "preferred", ""),

    # ============================================================
    # 十、程序与证据（Procedure & evidence）
    # ============================================================
    ("民事诉讼法", "Civil Procedure Law", "zh→en", "程序", "preferred", ""),
    ("刑事诉讼法", "Criminal Procedure Law", "zh→en", "程序", "preferred", ""),
    ("行政诉讼法", "Administrative Procedure Law", "zh→en", "程序", "preferred", ""),
    ("起诉", "institute an action", "zh→en", "程序", "strict", "to file a lawsuit"),
    ("立案", "filing of a case", "zh→en", "程序", "strict", "case filing"),
    ("受理", "acceptance of a case", "zh→en", "程序", "strict", ""),
    ("开庭审理", "court hearing", "zh→en", "程序", "strict", "trial"),
    ("法庭调查", "court investigation", "zh→en", "程序", "preferred", ""),
    ("法庭辩论", "court debate", "zh→en", "程序", "preferred", ""),
    ("最后陈述", "final statement", "zh→en", "程序", "preferred", ""),
    ("宣判", "pronouncement of judgment", "zh→en", "程序", "preferred", ""),
    ("送达", "service", "zh→en", "程序", "strict", "service of process"),
    ("传票", "summons", "zh→en", "程序", "strict", ""),
    ("拘传", "summons by compulsion", "zh→en", "程序", "preferred", ""),
    ("取保候审", "bail pending trial", "zh→en", "程序", "strict", ""),
    ("监视居住", "residential surveillance", "zh→en", "程序", "preferred", ""),
    ("拘留", "detention", "zh→en", "程序", "strict", ""),
    ("逮捕", "arrest", "zh→en", "程序", "strict", ""),
    ("搜查", "search", "zh→en", "程序", "strict", ""),
    ("扣押", "seizure", "zh→en", "程序", "strict", ""),
    ("鉴定", "expert evaluation", "zh→en", "程序", "strict", "forensic appraisal"),
    ("笔录", "written record", "zh→en", "程序", "preferred", ""),
    ("公诉", "public prosecution", "zh→en", "程序", "strict", ""),
    ("自诉", "private prosecution", "zh→en", "程序", "preferred", ""),
    ("抗诉", "protest", "zh→en", "程序", "preferred", "procuratorial protest"),
    ("简易程序", "summary procedure", "zh→en", "程序", "strict", ""),
    ("普通程序", "ordinary procedure", "zh→en", "程序", "preferred", ""),
    ("小额诉讼程序", "small claims procedure", "zh→en", "程序", "preferred", ""),

    # ============================================================
    # 十一、通用法律表达（General legal expressions）
    # ============================================================
    ("法律", "law", "zh→en", "通用", "preferred", ""),
    ("法规", "regulation", "zh→en", "通用", "preferred", ""),
    ("行政法规", "administrative regulation", "zh→en", "通用", "strict", ""),
    ("地方性法规", "local regulation", "zh→en", "通用", "preferred", ""),
    ("部门规章", "departmental rule", "zh→en", "通用", "preferred", ""),
    ("司法解释", "judicial interpretation", "zh→en", "通用", "strict", ""),
    ("法律效力", "legal effect", "zh→en", "通用", "strict", ""),
    ("溯及力", "retroactive effect", "zh→en", "通用", "preferred", ""),
    ("法的渊源", "source of law", "zh→en", "通用", "preferred", ""),
    ("成文法", "statutory law", "zh→en", "通用", "strict", ""),
    ("判例法", "case law", "zh→en", "通用", "strict", ""),
    ("普通法", "common law", "zh→en", "通用", "strict", ""),
    ("衡平法", "equity", "zh→en", "通用", "preferred", ""),
    ("大陆法系", "civil law system", "zh→en", "通用", "strict", ""),
    ("英美法系", "common law system", "zh→en", "通用", "strict", ""),
    ("法典", "code", "zh→en", "通用", "strict", ""),
    ("民法典", "Civil Code", "zh→en", "通用", "strict", ""),
    ("刑法典", "Criminal Code", "zh→en", "通用", "preferred", ""),
    ("宪法", "Constitution", "zh→en", "通用", "strict", ""),
    ("基本法", "Basic Law", "zh→en", "通用", "strict", ""),
    ("权利", "right", "zh→en", "通用", "strict", ""),
    ("义务", "obligation", "zh→en", "通用", "strict", "duty"),
    ("自然人", "natural person", "zh→en", "通用", "strict", ""),
    ("法人", "legal person", "zh→en", "通用", "strict", "legal entity"),
    ("非法人组织", "non-legal-person organization", "zh→en", "通用", "preferred", ""),
    ("民事权利能力", "capacity for civil rights", "zh→en", "通用", "strict", ""),
    ("民事行为能力", "capacity for civil conduct", "zh→en", "通用", "strict", ""),
    ("监护", "guardianship", "zh→en", "通用", "strict", ""),
    ("宣告失踪", "declaration of missing person", "zh→en", "通用", "preferred", ""),
    ("宣告死亡", "declaration of death", "zh→en", "通用", "preferred", ""),
    ("代理", "agency", "zh→en", "通用", "strict", ""),
    ("委托", "entrustment", "zh→en", "通用", "strict", "authorization"),
    ("授权", "authorization", "zh→en", "通用", "strict", ""),
    ("追认", "ratification", "zh→en", "通用", "preferred", ""),
    ("催告", "urging", "zh→en", "通用", "preferred", ""),
    ("撤销", "rescission", "zh→en", "通用", "strict", ""),
    ("无效", "null and void", "zh→en", "通用", "strict", ""),
    ("诉讼", "litigation", "zh→en", "通用", "strict", "lawsuit"),
    ("仲裁", "arbitration", "zh→en", "通用", "strict", ""),
    ("调解", "mediation", "zh→en", "通用", "strict", "conciliation"),
    ("和解", "settlement", "zh→en", "通用", "strict", ""),
    ("公证", "notarization", "zh→en", "通用", "strict", ""),
    ("律师", "lawyer", "zh→en", "通用", "strict", "attorney"),
    ("律师事务所", "law firm", "zh→en", "通用", "strict", ""),
    ("法律顾问", "legal counsel", "zh→en", "通用", "preferred", ""),
    ("法律意见书", "legal opinion", "zh→en", "通用", "strict", ""),
    ("尽职调查", "due diligence", "zh→en", "通用", "strict", "DD"),
    ("合规", "compliance", "zh→en", "通用", "strict", ""),
    ("免责", "exemption from liability", "zh→en", "通用", "preferred", ""),
    ("豁免", "waiver", "zh→en", "通用", "preferred", ""),
    ("管辖", "jurisdiction", "zh→en", "通用", "strict", ""),
    ("适用法律", "governing law", "zh→en", "通用", "strict", "applicable law"),
    ("准据法", "lex causae", "zh→en", "通用", "preferred", ""),
    ("国际私法", "private international law", "zh→en", "通用", "strict", "conflict of laws"),
    ("域外效力", "extraterritorial effect", "zh→en", "通用", "preferred", ""),
    ("国家主权", "state sovereignty", "zh→en", "通用", "strict", ""),
    ("豁免权", "immunity", "zh→en", "通用", "strict", ""),
    ("外交豁免", "diplomatic immunity", "zh→en", "通用", "preferred", ""),
    ("条约", "treaty", "zh→en", "通用", "strict", ""),
    ("公约", "convention", "zh→en", "通用", "strict", ""),
    ("协定", "agreement", "zh→en", "通用", "preferred", ""),
    ("议定书", "protocol", "zh→en", "通用", "preferred", ""),
    ("批准", "ratification", "zh→en", "通用", "strict", ""),
    ("生效", "entry into force", "zh→en", "通用", "strict", ""),
    ("终止", "termination", "zh→en", "通用", "strict", ""),
    ("中止", "suspension", "zh→en", "通用", "strict", ""),
    ("解除", "rescission", "zh→en", "通用", "strict", ""),
    ("废止", "repeal", "zh→en", "通用", "preferred", "abrogation"),
    ("修正", "amendment", "zh→en", "通用", "strict", ""),
    ("补充", "supplement", "zh→en", "通用", "preferred", ""),
    ("司法解释", "judicial interpretation", "zh→en", "通用", "strict", ""),
    ("指导性案例", "guiding case", "zh→en", "通用", "preferred", ""),
    ("公报案例", "gazette case", "zh→en", "通用", "preferred", ""),
]


def build_xlsx(output_path: str) -> int:
    """生成术语库 xlsx 文件，返回写入条目数。"""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "法律术语库"

    # 表头（与 _import_rows 期望的列顺序一致）
    ws.append(["中文术语", "目标语言术语", "语种方向", "领域标签", "优先级", "备注"])

    for row in TERMS:
        ws.append(list(row))

    wb.save(output_path)
    return len(TERMS)


if __name__ == "__main__":
    import os
    out = os.path.join(os.path.dirname(__file__), "法律术语库_中英.xlsx")
    count = build_xlsx(out)
    print(f"已生成：{out}")
    print(f"共 {count} 条术语")

    # 统计各领域数量
    from collections import Counter
    domain_count = Counter(row[3] for row in TERMS)
    priority_count = Counter(row[4] for row in TERMS)
    print("\n按领域分布：")
    for domain, n in sorted(domain_count.items(), key=lambda x: -x[1]):
        print(f"  {domain}: {n} 条")
    print("\n按优先级分布：")
    for priority, n in priority_count.items():
        print(f"  {priority}: {n} 条")
